#
# Copyright (c) 2011 FUJITSU TEN LIMITED and
# FUJITSU COMPUTER TECHNOLOGIES LIMITED. All rights reserved.
#

obj-$(CONFIG_LITES)	+= lites.o

lites-objs	+= mgmt_info.o kernel_panic_info.o printk.o region.o \
			dev.o var.o const.o ioctl.o trace_write.o buffer.o \
			parse.o syslog_init.o trace_init.o trace_fault_info.o
