header-y += audio.h
header-y += cdc.h
header-y += ch9.h
header-y += ch11.h
header-y += functionfs.h
header-y += gadgetfs.h
header-y += midi.h
header-y += g_printer.h
header-y += tmc.h
# FUJITSU TEN:2013-07-18 HTC mode. start
header-y += hsml_client.h
# FUJITSU TEN:2013-07-18 HTC mode. end
